---
title: "What's my Game?"
author: "Yuqing Xue"
date: "November 16, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)

library(highcharter)
```

## My Statistical Analysis for My Poker Statistics

### 1. Data Preparation

```{r}
#filePath <- file.choose()
filePath <- "/Users/apple/Desktop/YuqingRWork/Poker/DesciplinePokerAtheletes.xlsx"
GoogleSheet <- read_excel(filePath)

Testimate <- GoogleSheet %>% mutate(Date = ymd(Date), #sesStart = ymd_hms(sesStart), sesEnd = ymd_hms(sesEnd),
                             sesLength = as.numeric(sesEnd - sesStart), #directly make substraction between times
                             Profit = cashOut - buyIn, 
                             profitPerHr = Profit/sesLength,
                             totalProfit = promoBonus + Profit,
                             totalProfitPerHr = totalProfit/sesLength, 
                             accuHour = cumsum(sesLength),
                             accuProfit = cumsum(Profit), 
                             accuProfitPerHr = accuProfit/accuHour,
                             accuTotalProfit = cumsum(totalProfit),
                             accuTotalProfitPerHr = accuTotalProfit/accuHour); 

#options(tibble.width = Inf)  
#Testimate

```

 <https://r4ds.had.co.nz/tibbles.html> 10.3.1



### 2. Apply `htmlwidget` -> `highchater`

#### Initially inspired by [Philipp Spachtholz](https://www.kaggle.com/philippsp/interactive-dashboards-in-r)

#### Pacakge Author Joshua Kunst's RPub <https://rpubs.com/jbkunst/highcharter>

#### Additional `highcharter` learning material by [Danton Noriega](https://dantonnoriega.github.io/ultinomics.org/post/2017-04-05-highcharter-explainer.html) and [Nana Boateng](https://rstudio-pubs-static.s3.amazonaws.com/304105_70f2ad540827454e934117e3d90f6c1a.html)


```{r}
#library(highcharter)
series = list(
  list(
    name = 'Total Profit for One Session',
    color = '#1E90FF', # <http://cloford.com/resources/colours/500col.htm>
    data = Testimate %>% select(totalProfit) %>% .[[1]]
  )
)

highchart() %>%
  hc_add_series_list(series) %>% 
  hc_xAxis(categories = Testimate %>% select(Date) %>% .[[1]],
           plotBands = list(
             list(from = 2.5, to = 3.5, color = "rgba(68, 170, 213, 0.1)", label = list(text = "card dead, good discipline")),
             list(from = 3.5, to = 4.5, color = "#FAEBD7"),
             list(from = 4.5, to = 5.5, color = "rgba(68, 170, 213, 0.1)", label = list(text = "350$ cooler")),
             list(from = 5.5, to = 6.5, color = "#FAEBD7", label = list(text = "early Nit table")),
             list(from = 6.5, to = 7.5, color = "rgba(68, 170, 213, 0.1)", label = list(text = "400$ cooler")),
             list(from = 7.5, to = 8.5, color = "#FAEBD7", label = list(text = "hit 2 outer, gutter"))
             )) %>%
  hc_yAxis(plotLines = list(
             list(value = 0, width = 2, color = "black")
           ))
    
```

```{r}
series = list(
  list(
    name = 'Accumulate Total Profit (Counting Promo Bonus)',
    color = '#FFD700', 
    data = Testimate %>% select(accuTotalProfit) %>% .[[1]]
  )
)

highchart() %>%
  hc_add_series_list(series) %>% hc_xAxis(categories = Testimate %>% select(Date) %>% .[[1]])
```


```{r}
series = list(
  list(
    name = 'Accumulate Profit Per Hour',
    color = '#EEAD0E',
    data = Testimate %>% select(accuProfitPerHr) %>% .[[1]] %>% round(2) 
  ),
  list(
    name = 'Accumulate Total Profit Per Hour (Counting Promo Bonus)',
    color = '#FF7D40',
    data = Testimate %>% select(accuTotalProfitPerHr) %>% .[[1]] %>% round(2)
  )
)

highchart() %>%
  hc_add_series_list(series) %>% hc_xAxis(categories = Testimate %>% select(Date) %>% .[[1]])
```




`highcharter` seems to be outdated on CRAN. Directly install from github via

```
library(devtools)
install_github("jbkunst/highcharter")
```

